version: '3.4'

services:
  post.mongodb:
    container_name: post.mongodb
    restart: always
    ports:
       - "27017:27017"
    volumes:
       - mongo_data:/data/db
  post.sqldb:
    container_name: post.sqldb
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"